logging:
  level: INFO
  loggers:
    br.ufal.ic: DEBUG

#Database settings
database:
    #Driver
    driverClass: com.mysql.jdbc.Driver
    #username
    user: jvas
    #password
    password: 1234
    #JDBC URL
    url: jdbc:mysql://localhost:3306/drca